appId: com.effree.emspec
productName: EM-Spec
compression: maximum
directories:
  buildResources: assets
  output: dist

publish:
  provider: github
  owner: effree
  repo: EM-Spec

files:
  - main.js
  - renderer.js
  - index.html
  - style.css
  - assets/**/*
  - package.json
  - build/Release/*.node
  - "!**/*.md"
  - "!**/*.txt"
  - "!**/LICENSE*"
  - "!**/CHANGELOG*"
  - "!**/*.map"
  - "!**/test/**"
  - "!**/tests/**"
  - "!**/__tests__/**"
  - "!**/docs/**"
  - "!**/.github/**"
  - "!**/examples/**"
  - "!node_modules/.cache"

asarUnpack:
  - "**/*.node"

win:
  target:
    - target: nsis
      arch:
        - x64
  icon: assets/icon.ico
  artifactName: "${productName}-Setup-${version}.${ext}"

nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  perMachine: false
  deleteAppDataOnUninstall: true

mac:
  category: public.app-category.music
  target: dmg
  icon: assets/icon.icns
  identity: null
  artifactName: "${productName}-${version}-${arch}.${ext}"

afterPack: ./build-scripts/remove-licenses.js